/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSearchItemsRequestBody struct for GetSearchItemsRequestBody
type GetSearchItemsRequestBody struct {
	StartRow int32 `json:"startRow"`
	EndRow int32 `json:"endRow"`
	// 
	FilterModel map[string]interface{} `json:"filterModel,omitempty"`
	GroupKeys []string `json:"groupKeys,omitempty"`
	PivotCols []string `json:"pivotCols,omitempty"`
	PivotMode bool `json:"pivotMode"`
	RowGroupCols []string `json:"rowGroupCols,omitempty"`
	SortModel []SortModelItem `json:"sortModel,omitempty"`
	Tpl string `json:"tpl"`
	ValueCols []string `json:"valueCols,omitempty"`
}

// NewGetSearchItemsRequestBody instantiates a new GetSearchItemsRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSearchItemsRequestBody(startRow int32, endRow int32, pivotMode bool, tpl string) *GetSearchItemsRequestBody {
	this := GetSearchItemsRequestBody{}
	this.StartRow = startRow
	this.EndRow = endRow
	this.PivotMode = pivotMode
	this.Tpl = tpl
	return &this
}

// NewGetSearchItemsRequestBodyWithDefaults instantiates a new GetSearchItemsRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSearchItemsRequestBodyWithDefaults() *GetSearchItemsRequestBody {
	this := GetSearchItemsRequestBody{}
	return &this
}

// GetStartRow returns the StartRow field value
func (o *GetSearchItemsRequestBody) GetStartRow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartRow
}

// GetStartRowOk returns a tuple with the StartRow field value
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetStartRowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartRow, true
}

// SetStartRow sets field value
func (o *GetSearchItemsRequestBody) SetStartRow(v int32) {
	o.StartRow = v
}

// GetEndRow returns the EndRow field value
func (o *GetSearchItemsRequestBody) GetEndRow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndRow
}

// GetEndRowOk returns a tuple with the EndRow field value
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetEndRowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndRow, true
}

// SetEndRow sets field value
func (o *GetSearchItemsRequestBody) SetEndRow(v int32) {
	o.EndRow = v
}

// GetFilterModel returns the FilterModel field value if set, zero value otherwise.
func (o *GetSearchItemsRequestBody) GetFilterModel() map[string]interface{} {
	if o == nil || o.FilterModel == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.FilterModel
}

// GetFilterModelOk returns a tuple with the FilterModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetFilterModelOk() (map[string]interface{}, bool) {
	if o == nil || o.FilterModel == nil {
		return nil, false
	}
	return o.FilterModel, true
}

// HasFilterModel returns a boolean if a field has been set.
func (o *GetSearchItemsRequestBody) HasFilterModel() bool {
	if o != nil && o.FilterModel != nil {
		return true
	}

	return false
}

// SetFilterModel gets a reference to the given map[string]interface{} and assigns it to the FilterModel field.
func (o *GetSearchItemsRequestBody) SetFilterModel(v map[string]interface{}) {
	o.FilterModel = v
}

// GetGroupKeys returns the GroupKeys field value if set, zero value otherwise.
func (o *GetSearchItemsRequestBody) GetGroupKeys() []string {
	if o == nil || o.GroupKeys == nil {
		var ret []string
		return ret
	}
	return o.GroupKeys
}

// GetGroupKeysOk returns a tuple with the GroupKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetGroupKeysOk() ([]string, bool) {
	if o == nil || o.GroupKeys == nil {
		return nil, false
	}
	return o.GroupKeys, true
}

// HasGroupKeys returns a boolean if a field has been set.
func (o *GetSearchItemsRequestBody) HasGroupKeys() bool {
	if o != nil && o.GroupKeys != nil {
		return true
	}

	return false
}

// SetGroupKeys gets a reference to the given []string and assigns it to the GroupKeys field.
func (o *GetSearchItemsRequestBody) SetGroupKeys(v []string) {
	o.GroupKeys = v
}

// GetPivotCols returns the PivotCols field value if set, zero value otherwise.
func (o *GetSearchItemsRequestBody) GetPivotCols() []string {
	if o == nil || o.PivotCols == nil {
		var ret []string
		return ret
	}
	return o.PivotCols
}

// GetPivotColsOk returns a tuple with the PivotCols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetPivotColsOk() ([]string, bool) {
	if o == nil || o.PivotCols == nil {
		return nil, false
	}
	return o.PivotCols, true
}

// HasPivotCols returns a boolean if a field has been set.
func (o *GetSearchItemsRequestBody) HasPivotCols() bool {
	if o != nil && o.PivotCols != nil {
		return true
	}

	return false
}

// SetPivotCols gets a reference to the given []string and assigns it to the PivotCols field.
func (o *GetSearchItemsRequestBody) SetPivotCols(v []string) {
	o.PivotCols = v
}

// GetPivotMode returns the PivotMode field value
func (o *GetSearchItemsRequestBody) GetPivotMode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PivotMode
}

// GetPivotModeOk returns a tuple with the PivotMode field value
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetPivotModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PivotMode, true
}

// SetPivotMode sets field value
func (o *GetSearchItemsRequestBody) SetPivotMode(v bool) {
	o.PivotMode = v
}

// GetRowGroupCols returns the RowGroupCols field value if set, zero value otherwise.
func (o *GetSearchItemsRequestBody) GetRowGroupCols() []string {
	if o == nil || o.RowGroupCols == nil {
		var ret []string
		return ret
	}
	return o.RowGroupCols
}

// GetRowGroupColsOk returns a tuple with the RowGroupCols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetRowGroupColsOk() ([]string, bool) {
	if o == nil || o.RowGroupCols == nil {
		return nil, false
	}
	return o.RowGroupCols, true
}

// HasRowGroupCols returns a boolean if a field has been set.
func (o *GetSearchItemsRequestBody) HasRowGroupCols() bool {
	if o != nil && o.RowGroupCols != nil {
		return true
	}

	return false
}

// SetRowGroupCols gets a reference to the given []string and assigns it to the RowGroupCols field.
func (o *GetSearchItemsRequestBody) SetRowGroupCols(v []string) {
	o.RowGroupCols = v
}

// GetSortModel returns the SortModel field value if set, zero value otherwise.
func (o *GetSearchItemsRequestBody) GetSortModel() []SortModelItem {
	if o == nil || o.SortModel == nil {
		var ret []SortModelItem
		return ret
	}
	return o.SortModel
}

// GetSortModelOk returns a tuple with the SortModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetSortModelOk() ([]SortModelItem, bool) {
	if o == nil || o.SortModel == nil {
		return nil, false
	}
	return o.SortModel, true
}

// HasSortModel returns a boolean if a field has been set.
func (o *GetSearchItemsRequestBody) HasSortModel() bool {
	if o != nil && o.SortModel != nil {
		return true
	}

	return false
}

// SetSortModel gets a reference to the given []SortModelItem and assigns it to the SortModel field.
func (o *GetSearchItemsRequestBody) SetSortModel(v []SortModelItem) {
	o.SortModel = v
}

// GetTpl returns the Tpl field value
func (o *GetSearchItemsRequestBody) GetTpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tpl
}

// GetTplOk returns a tuple with the Tpl field value
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetTplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tpl, true
}

// SetTpl sets field value
func (o *GetSearchItemsRequestBody) SetTpl(v string) {
	o.Tpl = v
}

// GetValueCols returns the ValueCols field value if set, zero value otherwise.
func (o *GetSearchItemsRequestBody) GetValueCols() []string {
	if o == nil || o.ValueCols == nil {
		var ret []string
		return ret
	}
	return o.ValueCols
}

// GetValueColsOk returns a tuple with the ValueCols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSearchItemsRequestBody) GetValueColsOk() ([]string, bool) {
	if o == nil || o.ValueCols == nil {
		return nil, false
	}
	return o.ValueCols, true
}

// HasValueCols returns a boolean if a field has been set.
func (o *GetSearchItemsRequestBody) HasValueCols() bool {
	if o != nil && o.ValueCols != nil {
		return true
	}

	return false
}

// SetValueCols gets a reference to the given []string and assigns it to the ValueCols field.
func (o *GetSearchItemsRequestBody) SetValueCols(v []string) {
	o.ValueCols = v
}

func (o GetSearchItemsRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["startRow"] = o.StartRow
	}
	if true {
		toSerialize["endRow"] = o.EndRow
	}
	if o.FilterModel != nil {
		toSerialize["filterModel"] = o.FilterModel
	}
	if o.GroupKeys != nil {
		toSerialize["groupKeys"] = o.GroupKeys
	}
	if o.PivotCols != nil {
		toSerialize["pivotCols"] = o.PivotCols
	}
	if true {
		toSerialize["pivotMode"] = o.PivotMode
	}
	if o.RowGroupCols != nil {
		toSerialize["rowGroupCols"] = o.RowGroupCols
	}
	if o.SortModel != nil {
		toSerialize["sortModel"] = o.SortModel
	}
	if true {
		toSerialize["tpl"] = o.Tpl
	}
	if o.ValueCols != nil {
		toSerialize["valueCols"] = o.ValueCols
	}
	return json.Marshal(toSerialize)
}

type NullableGetSearchItemsRequestBody struct {
	value *GetSearchItemsRequestBody
	isSet bool
}

func (v NullableGetSearchItemsRequestBody) Get() *GetSearchItemsRequestBody {
	return v.value
}

func (v *NullableGetSearchItemsRequestBody) Set(val *GetSearchItemsRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSearchItemsRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSearchItemsRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSearchItemsRequestBody(val *GetSearchItemsRequestBody) *NullableGetSearchItemsRequestBody {
	return &NullableGetSearchItemsRequestBody{value: val, isSet: true}
}

func (v NullableGetSearchItemsRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSearchItemsRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


