/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CategoryUrl struct for CategoryUrl
type CategoryUrl struct {
	// Url на Wildberries
	Id string `json:"id"`
}

// NewCategoryUrl instantiates a new CategoryUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryUrl(id string) *CategoryUrl {
	this := CategoryUrl{}
	this.Id = id
	return &this
}

// NewCategoryUrlWithDefaults instantiates a new CategoryUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryUrlWithDefaults() *CategoryUrl {
	this := CategoryUrl{}
	return &this
}

// GetId returns the Id field value
func (o *CategoryUrl) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryUrl) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryUrl) SetId(v string) {
	o.Id = v
}

func (o CategoryUrl) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableCategoryUrl struct {
	value *CategoryUrl
	isSet bool
}

func (v NullableCategoryUrl) Get() *CategoryUrl {
	return v.value
}

func (v *NullableCategoryUrl) Set(val *CategoryUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryUrl(val *CategoryUrl) *NullableCategoryUrl {
	return &NullableCategoryUrl{value: val, isSet: true}
}

func (v NullableCategoryUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


