/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ItemBalanceByDay 
type ItemBalanceByDay struct {
	// Время
	Tm string `json:"tm"`
	// Остаток
	Balance int32 `json:"balance"`
	// Продажи
	Sales int32 `json:"sales"`
	// Рейтинг
	Rating float32 `json:"rating"`
	// Цена
	Price float32 `json:"price"`
	// Со скидкой
	FinalPrice float32 `json:"final_price"`
	// Комментариев
	Comments float32 `json:"comments"`
}

// NewItemBalanceByDay instantiates a new ItemBalanceByDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemBalanceByDay(tm string, balance int32, sales int32, rating float32, price float32, finalPrice float32, comments float32) *ItemBalanceByDay {
	this := ItemBalanceByDay{}
	this.Tm = tm
	this.Balance = balance
	this.Sales = sales
	this.Rating = rating
	this.Price = price
	this.FinalPrice = finalPrice
	this.Comments = comments
	return &this
}

// NewItemBalanceByDayWithDefaults instantiates a new ItemBalanceByDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemBalanceByDayWithDefaults() *ItemBalanceByDay {
	this := ItemBalanceByDay{}
	return &this
}

// GetTm returns the Tm field value
func (o *ItemBalanceByDay) GetTm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tm
}

// GetTmOk returns a tuple with the Tm field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetTmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tm, true
}

// SetTm sets field value
func (o *ItemBalanceByDay) SetTm(v string) {
	o.Tm = v
}

// GetBalance returns the Balance field value
func (o *ItemBalanceByDay) GetBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *ItemBalanceByDay) SetBalance(v int32) {
	o.Balance = v
}

// GetSales returns the Sales field value
func (o *ItemBalanceByDay) GetSales() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sales
}

// GetSalesOk returns a tuple with the Sales field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetSalesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sales, true
}

// SetSales sets field value
func (o *ItemBalanceByDay) SetSales(v int32) {
	o.Sales = v
}

// GetRating returns the Rating field value
func (o *ItemBalanceByDay) GetRating() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rating
}

// GetRatingOk returns a tuple with the Rating field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetRatingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rating, true
}

// SetRating sets field value
func (o *ItemBalanceByDay) SetRating(v float32) {
	o.Rating = v
}

// GetPrice returns the Price field value
func (o *ItemBalanceByDay) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *ItemBalanceByDay) SetPrice(v float32) {
	o.Price = v
}

// GetFinalPrice returns the FinalPrice field value
func (o *ItemBalanceByDay) GetFinalPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FinalPrice
}

// GetFinalPriceOk returns a tuple with the FinalPrice field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetFinalPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinalPrice, true
}

// SetFinalPrice sets field value
func (o *ItemBalanceByDay) SetFinalPrice(v float32) {
	o.FinalPrice = v
}

// GetComments returns the Comments field value
func (o *ItemBalanceByDay) GetComments() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value
// and a boolean to check if the value has been set.
func (o *ItemBalanceByDay) GetCommentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comments, true
}

// SetComments sets field value
func (o *ItemBalanceByDay) SetComments(v float32) {
	o.Comments = v
}

func (o ItemBalanceByDay) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tm"] = o.Tm
	}
	if true {
		toSerialize["balance"] = o.Balance
	}
	if true {
		toSerialize["sales"] = o.Sales
	}
	if true {
		toSerialize["rating"] = o.Rating
	}
	if true {
		toSerialize["price"] = o.Price
	}
	if true {
		toSerialize["final_price"] = o.FinalPrice
	}
	if true {
		toSerialize["comments"] = o.Comments
	}
	return json.Marshal(toSerialize)
}

type NullableItemBalanceByDay struct {
	value *ItemBalanceByDay
	isSet bool
}

func (v NullableItemBalanceByDay) Get() *ItemBalanceByDay {
	return v.value
}

func (v *NullableItemBalanceByDay) Set(val *ItemBalanceByDay) {
	v.value = val
	v.isSet = true
}

func (v NullableItemBalanceByDay) IsSet() bool {
	return v.isSet
}

func (v *NullableItemBalanceByDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemBalanceByDay(val *ItemBalanceByDay) *NullableItemBalanceByDay {
	return &NullableItemBalanceByDay{value: val, isSet: true}
}

func (v NullableItemBalanceByDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemBalanceByDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


