/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostRequestBody struct for PostRequestBody
type PostRequestBody struct {
	// Номер строки начала получения данных
	StartRow int32 `json:"startRow"`
	// Номер строки конца получения данных
	EndRow int32 `json:"endRow"`
	// 
	FilterModel interface{} `json:"filterModel"`
	SortModel []SortModelItem `json:"sortModel"`
}

// NewPostRequestBody instantiates a new PostRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRequestBody(startRow int32, endRow int32, filterModel interface{}, sortModel []SortModelItem) *PostRequestBody {
	this := PostRequestBody{}
	this.StartRow = startRow
	this.EndRow = endRow
	this.FilterModel = filterModel
	this.SortModel = sortModel
	return &this
}

// NewPostRequestBodyWithDefaults instantiates a new PostRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRequestBodyWithDefaults() *PostRequestBody {
	this := PostRequestBody{}
	return &this
}

// GetStartRow returns the StartRow field value
func (o *PostRequestBody) GetStartRow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartRow
}

// GetStartRowOk returns a tuple with the StartRow field value
// and a boolean to check if the value has been set.
func (o *PostRequestBody) GetStartRowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartRow, true
}

// SetStartRow sets field value
func (o *PostRequestBody) SetStartRow(v int32) {
	o.StartRow = v
}

// GetEndRow returns the EndRow field value
func (o *PostRequestBody) GetEndRow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndRow
}

// GetEndRowOk returns a tuple with the EndRow field value
// and a boolean to check if the value has been set.
func (o *PostRequestBody) GetEndRowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndRow, true
}

// SetEndRow sets field value
func (o *PostRequestBody) SetEndRow(v int32) {
	o.EndRow = v
}

// GetFilterModel returns the FilterModel field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PostRequestBody) GetFilterModel() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.FilterModel
}

// GetFilterModelOk returns a tuple with the FilterModel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostRequestBody) GetFilterModelOk() (*interface{}, bool) {
	if o == nil || o.FilterModel == nil {
		return nil, false
	}
	return &o.FilterModel, true
}

// SetFilterModel sets field value
func (o *PostRequestBody) SetFilterModel(v interface{}) {
	o.FilterModel = v
}

// GetSortModel returns the SortModel field value
func (o *PostRequestBody) GetSortModel() []SortModelItem {
	if o == nil {
		var ret []SortModelItem
		return ret
	}

	return o.SortModel
}

// GetSortModelOk returns a tuple with the SortModel field value
// and a boolean to check if the value has been set.
func (o *PostRequestBody) GetSortModelOk() ([]SortModelItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.SortModel, true
}

// SetSortModel sets field value
func (o *PostRequestBody) SetSortModel(v []SortModelItem) {
	o.SortModel = v
}

func (o PostRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["startRow"] = o.StartRow
	}
	if true {
		toSerialize["endRow"] = o.EndRow
	}
	if o.FilterModel != nil {
		toSerialize["filterModel"] = o.FilterModel
	}
	if true {
		toSerialize["sortModel"] = o.SortModel
	}
	return json.Marshal(toSerialize)
}

type NullablePostRequestBody struct {
	value *PostRequestBody
	isSet bool
}

func (v NullablePostRequestBody) Get() *PostRequestBody {
	return v.value
}

func (v *NullablePostRequestBody) Set(val *PostRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRequestBody(val *PostRequestBody) *NullablePostRequestBody {
	return &NullablePostRequestBody{value: val, isSet: true}
}

func (v NullablePostRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


