/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SellerPriceSegmentation 
type SellerPriceSegmentation struct {
	// Диапазон цен
	Range string `json:"range"`
	// Число товаров в диапазоне
	Items float32 `json:"items"`
	// Число брендов в диапазоне
	Brands float32 `json:"brands"`
	// Число брендов в диапазоне с продажами больше 0
	BrandsWithSells float32 `json:"brands_with_sells"`
	// Число продавцов в диапазоне
	Sellers float32 `json:"sellers"`
	// Число продавцов в диапазоне продажами больше 0
	SellersWithSells float32 `json:"sellers_with_sells"`
	// Суммарная выручка в диапазоне
	Revenue float32 `json:"revenue"`
	// Число продаж
	Sales float32 `json:"sales"`
	// Сумма выручки диапазона, разделенная на число товаров в нем
	ProductRevenue float32 `json:"product_revenue"`
	// Цена в диапазоне от
	MinRangePrice float32 `json:"min_range_price"`
	// Цена в диапазоне до
	MaxRangePrice float32 `json:"max_range_price"`
}

// NewSellerPriceSegmentation instantiates a new SellerPriceSegmentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSellerPriceSegmentation(range_ string, items float32, brands float32, brandsWithSells float32, sellers float32, sellersWithSells float32, revenue float32, sales float32, productRevenue float32, minRangePrice float32, maxRangePrice float32) *SellerPriceSegmentation {
	this := SellerPriceSegmentation{}
	this.Range = range_
	this.Items = items
	this.Brands = brands
	this.BrandsWithSells = brandsWithSells
	this.Sellers = sellers
	this.SellersWithSells = sellersWithSells
	this.Revenue = revenue
	this.Sales = sales
	this.ProductRevenue = productRevenue
	this.MinRangePrice = minRangePrice
	this.MaxRangePrice = maxRangePrice
	return &this
}

// NewSellerPriceSegmentationWithDefaults instantiates a new SellerPriceSegmentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSellerPriceSegmentationWithDefaults() *SellerPriceSegmentation {
	this := SellerPriceSegmentation{}
	return &this
}

// GetRange returns the Range field value
func (o *SellerPriceSegmentation) GetRange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetRangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Range, true
}

// SetRange sets field value
func (o *SellerPriceSegmentation) SetRange(v string) {
	o.Range = v
}

// GetItems returns the Items field value
func (o *SellerPriceSegmentation) GetItems() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetItemsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *SellerPriceSegmentation) SetItems(v float32) {
	o.Items = v
}

// GetBrands returns the Brands field value
func (o *SellerPriceSegmentation) GetBrands() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Brands
}

// GetBrandsOk returns a tuple with the Brands field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetBrandsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brands, true
}

// SetBrands sets field value
func (o *SellerPriceSegmentation) SetBrands(v float32) {
	o.Brands = v
}

// GetBrandsWithSells returns the BrandsWithSells field value
func (o *SellerPriceSegmentation) GetBrandsWithSells() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BrandsWithSells
}

// GetBrandsWithSellsOk returns a tuple with the BrandsWithSells field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetBrandsWithSellsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrandsWithSells, true
}

// SetBrandsWithSells sets field value
func (o *SellerPriceSegmentation) SetBrandsWithSells(v float32) {
	o.BrandsWithSells = v
}

// GetSellers returns the Sellers field value
func (o *SellerPriceSegmentation) GetSellers() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Sellers
}

// GetSellersOk returns a tuple with the Sellers field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetSellersOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sellers, true
}

// SetSellers sets field value
func (o *SellerPriceSegmentation) SetSellers(v float32) {
	o.Sellers = v
}

// GetSellersWithSells returns the SellersWithSells field value
func (o *SellerPriceSegmentation) GetSellersWithSells() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SellersWithSells
}

// GetSellersWithSellsOk returns a tuple with the SellersWithSells field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetSellersWithSellsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SellersWithSells, true
}

// SetSellersWithSells sets field value
func (o *SellerPriceSegmentation) SetSellersWithSells(v float32) {
	o.SellersWithSells = v
}

// GetRevenue returns the Revenue field value
func (o *SellerPriceSegmentation) GetRevenue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetRevenueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revenue, true
}

// SetRevenue sets field value
func (o *SellerPriceSegmentation) SetRevenue(v float32) {
	o.Revenue = v
}

// GetSales returns the Sales field value
func (o *SellerPriceSegmentation) GetSales() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Sales
}

// GetSalesOk returns a tuple with the Sales field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetSalesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sales, true
}

// SetSales sets field value
func (o *SellerPriceSegmentation) SetSales(v float32) {
	o.Sales = v
}

// GetProductRevenue returns the ProductRevenue field value
func (o *SellerPriceSegmentation) GetProductRevenue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProductRevenue
}

// GetProductRevenueOk returns a tuple with the ProductRevenue field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetProductRevenueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductRevenue, true
}

// SetProductRevenue sets field value
func (o *SellerPriceSegmentation) SetProductRevenue(v float32) {
	o.ProductRevenue = v
}

// GetMinRangePrice returns the MinRangePrice field value
func (o *SellerPriceSegmentation) GetMinRangePrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MinRangePrice
}

// GetMinRangePriceOk returns a tuple with the MinRangePrice field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetMinRangePriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinRangePrice, true
}

// SetMinRangePrice sets field value
func (o *SellerPriceSegmentation) SetMinRangePrice(v float32) {
	o.MinRangePrice = v
}

// GetMaxRangePrice returns the MaxRangePrice field value
func (o *SellerPriceSegmentation) GetMaxRangePrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MaxRangePrice
}

// GetMaxRangePriceOk returns a tuple with the MaxRangePrice field value
// and a boolean to check if the value has been set.
func (o *SellerPriceSegmentation) GetMaxRangePriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxRangePrice, true
}

// SetMaxRangePrice sets field value
func (o *SellerPriceSegmentation) SetMaxRangePrice(v float32) {
	o.MaxRangePrice = v
}

func (o SellerPriceSegmentation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["range"] = o.Range
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["brands"] = o.Brands
	}
	if true {
		toSerialize["brands_with_sells"] = o.BrandsWithSells
	}
	if true {
		toSerialize["sellers"] = o.Sellers
	}
	if true {
		toSerialize["sellers_with_sells"] = o.SellersWithSells
	}
	if true {
		toSerialize["revenue"] = o.Revenue
	}
	if true {
		toSerialize["sales"] = o.Sales
	}
	if true {
		toSerialize["product_revenue"] = o.ProductRevenue
	}
	if true {
		toSerialize["min_range_price"] = o.MinRangePrice
	}
	if true {
		toSerialize["max_range_price"] = o.MaxRangePrice
	}
	return json.Marshal(toSerialize)
}

type NullableSellerPriceSegmentation struct {
	value *SellerPriceSegmentation
	isSet bool
}

func (v NullableSellerPriceSegmentation) Get() *SellerPriceSegmentation {
	return v.value
}

func (v *NullableSellerPriceSegmentation) Set(val *SellerPriceSegmentation) {
	v.value = val
	v.isSet = true
}

func (v NullableSellerPriceSegmentation) IsSet() bool {
	return v.isSet
}

func (v *NullableSellerPriceSegmentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSellerPriceSegmentation(val *SellerPriceSegmentation) *NullableSellerPriceSegmentation {
	return &NullableSellerPriceSegmentation{value: val, isSet: true}
}

func (v NullableSellerPriceSegmentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSellerPriceSegmentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


