/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ItemSimilar 
type ItemSimilar struct {
	// Последний зафиксированный остаток на складе
	Balance float32 `json:"balance"`
	// Название бренда
	Brand string `json:"brand"`
	// Количество комментариев
	Comments float32 `json:"comments"`
	// Последняя зафиксированная цена
	FinalPrice float32 `json:"final_price"`
	// График продаж
	Graph []int32 `json:"graph"`
	// SKU
	Id float32 `json:"id"`
	// Название товара
	Name string `json:"name"`
	// Рейтинг товара
	Rating float32 `json:"rating"`
	// Выручка за период
	Revenue float32 `json:"revenue"`
	// Количество проданных единиц товара за период
	Sales float32 `json:"sales"`
	// Название продавца
	Seller string `json:"seller"`
	// Изображение товара
	Thumb string `json:"thumb"`
	// Изображение товара (среднее)
	ThumbMiddle string `json:"thumb_middle"`
}

// NewItemSimilar instantiates a new ItemSimilar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemSimilar(balance float32, brand string, comments float32, finalPrice float32, graph []int32, id float32, name string, rating float32, revenue float32, sales float32, seller string, thumb string, thumbMiddle string) *ItemSimilar {
	this := ItemSimilar{}
	this.Balance = balance
	this.Brand = brand
	this.Comments = comments
	this.FinalPrice = finalPrice
	this.Graph = graph
	this.Id = id
	this.Name = name
	this.Rating = rating
	this.Revenue = revenue
	this.Sales = sales
	this.Seller = seller
	this.Thumb = thumb
	this.ThumbMiddle = thumbMiddle
	return &this
}

// NewItemSimilarWithDefaults instantiates a new ItemSimilar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemSimilarWithDefaults() *ItemSimilar {
	this := ItemSimilar{}
	return &this
}

// GetBalance returns the Balance field value
func (o *ItemSimilar) GetBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *ItemSimilar) SetBalance(v float32) {
	o.Balance = v
}

// GetBrand returns the Brand field value
func (o *ItemSimilar) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *ItemSimilar) SetBrand(v string) {
	o.Brand = v
}

// GetComments returns the Comments field value
func (o *ItemSimilar) GetComments() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetCommentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comments, true
}

// SetComments sets field value
func (o *ItemSimilar) SetComments(v float32) {
	o.Comments = v
}

// GetFinalPrice returns the FinalPrice field value
func (o *ItemSimilar) GetFinalPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FinalPrice
}

// GetFinalPriceOk returns a tuple with the FinalPrice field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetFinalPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinalPrice, true
}

// SetFinalPrice sets field value
func (o *ItemSimilar) SetFinalPrice(v float32) {
	o.FinalPrice = v
}

// GetGraph returns the Graph field value
func (o *ItemSimilar) GetGraph() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Graph
}

// GetGraphOk returns a tuple with the Graph field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetGraphOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Graph, true
}

// SetGraph sets field value
func (o *ItemSimilar) SetGraph(v []int32) {
	o.Graph = v
}

// GetId returns the Id field value
func (o *ItemSimilar) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ItemSimilar) SetId(v float32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ItemSimilar) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ItemSimilar) SetName(v string) {
	o.Name = v
}

// GetRating returns the Rating field value
func (o *ItemSimilar) GetRating() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rating
}

// GetRatingOk returns a tuple with the Rating field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetRatingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rating, true
}

// SetRating sets field value
func (o *ItemSimilar) SetRating(v float32) {
	o.Rating = v
}

// GetRevenue returns the Revenue field value
func (o *ItemSimilar) GetRevenue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetRevenueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revenue, true
}

// SetRevenue sets field value
func (o *ItemSimilar) SetRevenue(v float32) {
	o.Revenue = v
}

// GetSales returns the Sales field value
func (o *ItemSimilar) GetSales() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Sales
}

// GetSalesOk returns a tuple with the Sales field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetSalesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sales, true
}

// SetSales sets field value
func (o *ItemSimilar) SetSales(v float32) {
	o.Sales = v
}

// GetSeller returns the Seller field value
func (o *ItemSimilar) GetSeller() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Seller
}

// GetSellerOk returns a tuple with the Seller field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetSellerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seller, true
}

// SetSeller sets field value
func (o *ItemSimilar) SetSeller(v string) {
	o.Seller = v
}

// GetThumb returns the Thumb field value
func (o *ItemSimilar) GetThumb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetThumbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumb, true
}

// SetThumb sets field value
func (o *ItemSimilar) SetThumb(v string) {
	o.Thumb = v
}

// GetThumbMiddle returns the ThumbMiddle field value
func (o *ItemSimilar) GetThumbMiddle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThumbMiddle
}

// GetThumbMiddleOk returns a tuple with the ThumbMiddle field value
// and a boolean to check if the value has been set.
func (o *ItemSimilar) GetThumbMiddleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThumbMiddle, true
}

// SetThumbMiddle sets field value
func (o *ItemSimilar) SetThumbMiddle(v string) {
	o.ThumbMiddle = v
}

func (o ItemSimilar) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["balance"] = o.Balance
	}
	if true {
		toSerialize["brand"] = o.Brand
	}
	if true {
		toSerialize["comments"] = o.Comments
	}
	if true {
		toSerialize["final_price"] = o.FinalPrice
	}
	if true {
		toSerialize["graph"] = o.Graph
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["rating"] = o.Rating
	}
	if true {
		toSerialize["revenue"] = o.Revenue
	}
	if true {
		toSerialize["sales"] = o.Sales
	}
	if true {
		toSerialize["seller"] = o.Seller
	}
	if true {
		toSerialize["thumb"] = o.Thumb
	}
	if true {
		toSerialize["thumb_middle"] = o.ThumbMiddle
	}
	return json.Marshal(toSerialize)
}

type NullableItemSimilar struct {
	value *ItemSimilar
	isSet bool
}

func (v NullableItemSimilar) Get() *ItemSimilar {
	return v.value
}

func (v *NullableItemSimilar) Set(val *ItemSimilar) {
	v.value = val
	v.isSet = true
}

func (v NullableItemSimilar) IsSet() bool {
	return v.isSet
}

func (v *NullableItemSimilar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemSimilar(val *ItemSimilar) *NullableItemSimilar {
	return &NullableItemSimilar{value: val, isSet: true}
}

func (v NullableItemSimilar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemSimilar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


