/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BrandCategory 
type BrandCategory struct {
	// Название бренда
	Name string `json:"name"`
	// Число товаров
	Items int32 `json:"items"`
	// Число зафиксированных продаж (единицы)
	Sales int32 `json:"sales"`
	// Сумма произведений числа проданных товаров на их стоимость
	Revenue float32 `json:"revenue"`
	// Среднее число комментариев
	Comments float32 `json:"comments"`
	// Средний рейтинг
	Rating float32 `json:"rating"`
}

// NewBrandCategory instantiates a new BrandCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandCategory(name string, items int32, sales int32, revenue float32, comments float32, rating float32) *BrandCategory {
	this := BrandCategory{}
	this.Name = name
	this.Items = items
	this.Sales = sales
	this.Revenue = revenue
	this.Comments = comments
	this.Rating = rating
	return &this
}

// NewBrandCategoryWithDefaults instantiates a new BrandCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandCategoryWithDefaults() *BrandCategory {
	this := BrandCategory{}
	return &this
}

// GetName returns the Name field value
func (o *BrandCategory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BrandCategory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BrandCategory) SetName(v string) {
	o.Name = v
}

// GetItems returns the Items field value
func (o *BrandCategory) GetItems() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *BrandCategory) GetItemsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *BrandCategory) SetItems(v int32) {
	o.Items = v
}

// GetSales returns the Sales field value
func (o *BrandCategory) GetSales() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sales
}

// GetSalesOk returns a tuple with the Sales field value
// and a boolean to check if the value has been set.
func (o *BrandCategory) GetSalesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sales, true
}

// SetSales sets field value
func (o *BrandCategory) SetSales(v int32) {
	o.Sales = v
}

// GetRevenue returns the Revenue field value
func (o *BrandCategory) GetRevenue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value
// and a boolean to check if the value has been set.
func (o *BrandCategory) GetRevenueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revenue, true
}

// SetRevenue sets field value
func (o *BrandCategory) SetRevenue(v float32) {
	o.Revenue = v
}

// GetComments returns the Comments field value
func (o *BrandCategory) GetComments() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value
// and a boolean to check if the value has been set.
func (o *BrandCategory) GetCommentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comments, true
}

// SetComments sets field value
func (o *BrandCategory) SetComments(v float32) {
	o.Comments = v
}

// GetRating returns the Rating field value
func (o *BrandCategory) GetRating() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rating
}

// GetRatingOk returns a tuple with the Rating field value
// and a boolean to check if the value has been set.
func (o *BrandCategory) GetRatingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rating, true
}

// SetRating sets field value
func (o *BrandCategory) SetRating(v float32) {
	o.Rating = v
}

func (o BrandCategory) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["sales"] = o.Sales
	}
	if true {
		toSerialize["revenue"] = o.Revenue
	}
	if true {
		toSerialize["comments"] = o.Comments
	}
	if true {
		toSerialize["rating"] = o.Rating
	}
	return json.Marshal(toSerialize)
}

type NullableBrandCategory struct {
	value *BrandCategory
	isSet bool
}

func (v NullableBrandCategory) Get() *BrandCategory {
	return v.value
}

func (v *NullableBrandCategory) Set(val *BrandCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandCategory(val *BrandCategory) *NullableBrandCategory {
	return &NullableBrandCategory{value: val, isSet: true}
}

func (v NullableBrandCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


