/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SearchCategoriesItem struct for SearchCategoriesItem
type SearchCategoriesItem struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Brand *string `json:"brand,omitempty"`
	Seller *string `json:"seller,omitempty"`
	SupplierId *int32 `json:"supplier_id,omitempty"`
	Category *string `json:"category,omitempty"`
	CategoryPosition *int32 `json:"category_position,omitempty"`
	PosData *string `json:"pos_data,omitempty"`
	Color *string `json:"color,omitempty"`
	Balance *int32 `json:"balance,omitempty"`
	BalanceFbs *int32 `json:"balance_fbs,omitempty"`
	Comments *int32 `json:"comments,omitempty"`
	Rating *int32 `json:"rating,omitempty"`
	FinalPrice *int32 `json:"final_price,omitempty"`
	FinalPriceMax *int32 `json:"final_price_max,omitempty"`
	FinalPriceMin *int32 `json:"final_price_min,omitempty"`
	FinalPriceAverage *int32 `json:"final_price_average,omitempty"`
	BasicSale *int32 `json:"basic_sale,omitempty"`
	BasicPrice *int32 `json:"basic_price,omitempty"`
	PromoSale *int32 `json:"promo_sale,omitempty"`
	ClientSale *int32 `json:"client_sale,omitempty"`
	ClientPrice *int32 `json:"client_price,omitempty"`
	StartPrice *int32 `json:"start_price,omitempty"`
	Sales *int32 `json:"sales,omitempty"`
	SalesPerDayAverage *float32 `json:"sales_per_day_average,omitempty"`
	Revenue *int32 `json:"revenue,omitempty"`
	RevenuePotential *int32 `json:"revenue_potential,omitempty"`
	LostProfit *int32 `json:"lost_profit,omitempty"`
	LostProfitPercent *float32 `json:"lost_profit_percent,omitempty"`
	DaysInStock *int32 `json:"days_in_stock,omitempty"`
	DaysWithSales *int32 `json:"days_with_sales,omitempty"`
	AverageIfInStock *float32 `json:"average_if_in_stock,omitempty"`
	Thumb *string `json:"thumb,omitempty"`
	ThumbMiddle *string `json:"thumb_middle,omitempty"`
	IsFbs *int32 `json:"is_fbs,omitempty"`
	SubjectId *int32 `json:"subject_id,omitempty"`
	Url *string `json:"url,omitempty"`
	Country *string `json:"country,omitempty"`
	Gender *string `json:"gender,omitempty"`
	SkuFirstDate *string `json:"sku_first_date,omitempty"`
	Firstcommentdate *string `json:"firstcommentdate,omitempty"`
	Picscount *int32 `json:"picscount,omitempty"`
	Has3d *int32 `json:"has3d,omitempty"`
	Hasvideo *int32 `json:"hasvideo,omitempty"`
	Commentsvaluation *float32 `json:"commentsvaluation,omitempty"`
	Cardratingval *int32 `json:"cardratingval,omitempty"`
	Position *int32 `json:"position,omitempty"`
	CategoriesLastCount *string `json:"categories_last_count,omitempty"`
	Graph []int32 `json:"graph,omitempty"`
	CategoryGraph []int32 `json:"category_graph,omitempty"`
	StocksGraph []int32 `json:"stocks_graph,omitempty"`
	PriceGraph []int32 `json:"price_graph,omitempty"`
}

// NewSearchCategoriesItem instantiates a new SearchCategoriesItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCategoriesItem() *SearchCategoriesItem {
	this := SearchCategoriesItem{}
	return &this
}

// NewSearchCategoriesItemWithDefaults instantiates a new SearchCategoriesItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCategoriesItemWithDefaults() *SearchCategoriesItem {
	this := SearchCategoriesItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *SearchCategoriesItem) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SearchCategoriesItem) SetName(v string) {
	o.Name = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetBrand() string {
	if o == nil || o.Brand == nil {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetBrandOk() (*string, bool) {
	if o == nil || o.Brand == nil {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasBrand() bool {
	if o != nil && o.Brand != nil {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *SearchCategoriesItem) SetBrand(v string) {
	o.Brand = &v
}

// GetSeller returns the Seller field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetSeller() string {
	if o == nil || o.Seller == nil {
		var ret string
		return ret
	}
	return *o.Seller
}

// GetSellerOk returns a tuple with the Seller field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetSellerOk() (*string, bool) {
	if o == nil || o.Seller == nil {
		return nil, false
	}
	return o.Seller, true
}

// HasSeller returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasSeller() bool {
	if o != nil && o.Seller != nil {
		return true
	}

	return false
}

// SetSeller gets a reference to the given string and assigns it to the Seller field.
func (o *SearchCategoriesItem) SetSeller(v string) {
	o.Seller = &v
}

// GetSupplierId returns the SupplierId field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetSupplierId() int32 {
	if o == nil || o.SupplierId == nil {
		var ret int32
		return ret
	}
	return *o.SupplierId
}

// GetSupplierIdOk returns a tuple with the SupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetSupplierIdOk() (*int32, bool) {
	if o == nil || o.SupplierId == nil {
		return nil, false
	}
	return o.SupplierId, true
}

// HasSupplierId returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasSupplierId() bool {
	if o != nil && o.SupplierId != nil {
		return true
	}

	return false
}

// SetSupplierId gets a reference to the given int32 and assigns it to the SupplierId field.
func (o *SearchCategoriesItem) SetSupplierId(v int32) {
	o.SupplierId = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCategory() string {
	if o == nil || o.Category == nil {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCategoryOk() (*string, bool) {
	if o == nil || o.Category == nil {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCategory() bool {
	if o != nil && o.Category != nil {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *SearchCategoriesItem) SetCategory(v string) {
	o.Category = &v
}

// GetCategoryPosition returns the CategoryPosition field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCategoryPosition() int32 {
	if o == nil || o.CategoryPosition == nil {
		var ret int32
		return ret
	}
	return *o.CategoryPosition
}

// GetCategoryPositionOk returns a tuple with the CategoryPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCategoryPositionOk() (*int32, bool) {
	if o == nil || o.CategoryPosition == nil {
		return nil, false
	}
	return o.CategoryPosition, true
}

// HasCategoryPosition returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCategoryPosition() bool {
	if o != nil && o.CategoryPosition != nil {
		return true
	}

	return false
}

// SetCategoryPosition gets a reference to the given int32 and assigns it to the CategoryPosition field.
func (o *SearchCategoriesItem) SetCategoryPosition(v int32) {
	o.CategoryPosition = &v
}

// GetPosData returns the PosData field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetPosData() string {
	if o == nil || o.PosData == nil {
		var ret string
		return ret
	}
	return *o.PosData
}

// GetPosDataOk returns a tuple with the PosData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetPosDataOk() (*string, bool) {
	if o == nil || o.PosData == nil {
		return nil, false
	}
	return o.PosData, true
}

// HasPosData returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasPosData() bool {
	if o != nil && o.PosData != nil {
		return true
	}

	return false
}

// SetPosData gets a reference to the given string and assigns it to the PosData field.
func (o *SearchCategoriesItem) SetPosData(v string) {
	o.PosData = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetColor() string {
	if o == nil || o.Color == nil {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetColorOk() (*string, bool) {
	if o == nil || o.Color == nil {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasColor() bool {
	if o != nil && o.Color != nil {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *SearchCategoriesItem) SetColor(v string) {
	o.Color = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetBalance() int32 {
	if o == nil || o.Balance == nil {
		var ret int32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetBalanceOk() (*int32, bool) {
	if o == nil || o.Balance == nil {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasBalance() bool {
	if o != nil && o.Balance != nil {
		return true
	}

	return false
}

// SetBalance gets a reference to the given int32 and assigns it to the Balance field.
func (o *SearchCategoriesItem) SetBalance(v int32) {
	o.Balance = &v
}

// GetBalanceFbs returns the BalanceFbs field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetBalanceFbs() int32 {
	if o == nil || o.BalanceFbs == nil {
		var ret int32
		return ret
	}
	return *o.BalanceFbs
}

// GetBalanceFbsOk returns a tuple with the BalanceFbs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetBalanceFbsOk() (*int32, bool) {
	if o == nil || o.BalanceFbs == nil {
		return nil, false
	}
	return o.BalanceFbs, true
}

// HasBalanceFbs returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasBalanceFbs() bool {
	if o != nil && o.BalanceFbs != nil {
		return true
	}

	return false
}

// SetBalanceFbs gets a reference to the given int32 and assigns it to the BalanceFbs field.
func (o *SearchCategoriesItem) SetBalanceFbs(v int32) {
	o.BalanceFbs = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetComments() int32 {
	if o == nil || o.Comments == nil {
		var ret int32
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCommentsOk() (*int32, bool) {
	if o == nil || o.Comments == nil {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasComments() bool {
	if o != nil && o.Comments != nil {
		return true
	}

	return false
}

// SetComments gets a reference to the given int32 and assigns it to the Comments field.
func (o *SearchCategoriesItem) SetComments(v int32) {
	o.Comments = &v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetRating() int32 {
	if o == nil || o.Rating == nil {
		var ret int32
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetRatingOk() (*int32, bool) {
	if o == nil || o.Rating == nil {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasRating() bool {
	if o != nil && o.Rating != nil {
		return true
	}

	return false
}

// SetRating gets a reference to the given int32 and assigns it to the Rating field.
func (o *SearchCategoriesItem) SetRating(v int32) {
	o.Rating = &v
}

// GetFinalPrice returns the FinalPrice field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetFinalPrice() int32 {
	if o == nil || o.FinalPrice == nil {
		var ret int32
		return ret
	}
	return *o.FinalPrice
}

// GetFinalPriceOk returns a tuple with the FinalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetFinalPriceOk() (*int32, bool) {
	if o == nil || o.FinalPrice == nil {
		return nil, false
	}
	return o.FinalPrice, true
}

// HasFinalPrice returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasFinalPrice() bool {
	if o != nil && o.FinalPrice != nil {
		return true
	}

	return false
}

// SetFinalPrice gets a reference to the given int32 and assigns it to the FinalPrice field.
func (o *SearchCategoriesItem) SetFinalPrice(v int32) {
	o.FinalPrice = &v
}

// GetFinalPriceMax returns the FinalPriceMax field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetFinalPriceMax() int32 {
	if o == nil || o.FinalPriceMax == nil {
		var ret int32
		return ret
	}
	return *o.FinalPriceMax
}

// GetFinalPriceMaxOk returns a tuple with the FinalPriceMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetFinalPriceMaxOk() (*int32, bool) {
	if o == nil || o.FinalPriceMax == nil {
		return nil, false
	}
	return o.FinalPriceMax, true
}

// HasFinalPriceMax returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasFinalPriceMax() bool {
	if o != nil && o.FinalPriceMax != nil {
		return true
	}

	return false
}

// SetFinalPriceMax gets a reference to the given int32 and assigns it to the FinalPriceMax field.
func (o *SearchCategoriesItem) SetFinalPriceMax(v int32) {
	o.FinalPriceMax = &v
}

// GetFinalPriceMin returns the FinalPriceMin field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetFinalPriceMin() int32 {
	if o == nil || o.FinalPriceMin == nil {
		var ret int32
		return ret
	}
	return *o.FinalPriceMin
}

// GetFinalPriceMinOk returns a tuple with the FinalPriceMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetFinalPriceMinOk() (*int32, bool) {
	if o == nil || o.FinalPriceMin == nil {
		return nil, false
	}
	return o.FinalPriceMin, true
}

// HasFinalPriceMin returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasFinalPriceMin() bool {
	if o != nil && o.FinalPriceMin != nil {
		return true
	}

	return false
}

// SetFinalPriceMin gets a reference to the given int32 and assigns it to the FinalPriceMin field.
func (o *SearchCategoriesItem) SetFinalPriceMin(v int32) {
	o.FinalPriceMin = &v
}

// GetFinalPriceAverage returns the FinalPriceAverage field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetFinalPriceAverage() int32 {
	if o == nil || o.FinalPriceAverage == nil {
		var ret int32
		return ret
	}
	return *o.FinalPriceAverage
}

// GetFinalPriceAverageOk returns a tuple with the FinalPriceAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetFinalPriceAverageOk() (*int32, bool) {
	if o == nil || o.FinalPriceAverage == nil {
		return nil, false
	}
	return o.FinalPriceAverage, true
}

// HasFinalPriceAverage returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasFinalPriceAverage() bool {
	if o != nil && o.FinalPriceAverage != nil {
		return true
	}

	return false
}

// SetFinalPriceAverage gets a reference to the given int32 and assigns it to the FinalPriceAverage field.
func (o *SearchCategoriesItem) SetFinalPriceAverage(v int32) {
	o.FinalPriceAverage = &v
}

// GetBasicSale returns the BasicSale field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetBasicSale() int32 {
	if o == nil || o.BasicSale == nil {
		var ret int32
		return ret
	}
	return *o.BasicSale
}

// GetBasicSaleOk returns a tuple with the BasicSale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetBasicSaleOk() (*int32, bool) {
	if o == nil || o.BasicSale == nil {
		return nil, false
	}
	return o.BasicSale, true
}

// HasBasicSale returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasBasicSale() bool {
	if o != nil && o.BasicSale != nil {
		return true
	}

	return false
}

// SetBasicSale gets a reference to the given int32 and assigns it to the BasicSale field.
func (o *SearchCategoriesItem) SetBasicSale(v int32) {
	o.BasicSale = &v
}

// GetBasicPrice returns the BasicPrice field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetBasicPrice() int32 {
	if o == nil || o.BasicPrice == nil {
		var ret int32
		return ret
	}
	return *o.BasicPrice
}

// GetBasicPriceOk returns a tuple with the BasicPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetBasicPriceOk() (*int32, bool) {
	if o == nil || o.BasicPrice == nil {
		return nil, false
	}
	return o.BasicPrice, true
}

// HasBasicPrice returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasBasicPrice() bool {
	if o != nil && o.BasicPrice != nil {
		return true
	}

	return false
}

// SetBasicPrice gets a reference to the given int32 and assigns it to the BasicPrice field.
func (o *SearchCategoriesItem) SetBasicPrice(v int32) {
	o.BasicPrice = &v
}

// GetPromoSale returns the PromoSale field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetPromoSale() int32 {
	if o == nil || o.PromoSale == nil {
		var ret int32
		return ret
	}
	return *o.PromoSale
}

// GetPromoSaleOk returns a tuple with the PromoSale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetPromoSaleOk() (*int32, bool) {
	if o == nil || o.PromoSale == nil {
		return nil, false
	}
	return o.PromoSale, true
}

// HasPromoSale returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasPromoSale() bool {
	if o != nil && o.PromoSale != nil {
		return true
	}

	return false
}

// SetPromoSale gets a reference to the given int32 and assigns it to the PromoSale field.
func (o *SearchCategoriesItem) SetPromoSale(v int32) {
	o.PromoSale = &v
}

// GetClientSale returns the ClientSale field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetClientSale() int32 {
	if o == nil || o.ClientSale == nil {
		var ret int32
		return ret
	}
	return *o.ClientSale
}

// GetClientSaleOk returns a tuple with the ClientSale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetClientSaleOk() (*int32, bool) {
	if o == nil || o.ClientSale == nil {
		return nil, false
	}
	return o.ClientSale, true
}

// HasClientSale returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasClientSale() bool {
	if o != nil && o.ClientSale != nil {
		return true
	}

	return false
}

// SetClientSale gets a reference to the given int32 and assigns it to the ClientSale field.
func (o *SearchCategoriesItem) SetClientSale(v int32) {
	o.ClientSale = &v
}

// GetClientPrice returns the ClientPrice field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetClientPrice() int32 {
	if o == nil || o.ClientPrice == nil {
		var ret int32
		return ret
	}
	return *o.ClientPrice
}

// GetClientPriceOk returns a tuple with the ClientPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetClientPriceOk() (*int32, bool) {
	if o == nil || o.ClientPrice == nil {
		return nil, false
	}
	return o.ClientPrice, true
}

// HasClientPrice returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasClientPrice() bool {
	if o != nil && o.ClientPrice != nil {
		return true
	}

	return false
}

// SetClientPrice gets a reference to the given int32 and assigns it to the ClientPrice field.
func (o *SearchCategoriesItem) SetClientPrice(v int32) {
	o.ClientPrice = &v
}

// GetStartPrice returns the StartPrice field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetStartPrice() int32 {
	if o == nil || o.StartPrice == nil {
		var ret int32
		return ret
	}
	return *o.StartPrice
}

// GetStartPriceOk returns a tuple with the StartPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetStartPriceOk() (*int32, bool) {
	if o == nil || o.StartPrice == nil {
		return nil, false
	}
	return o.StartPrice, true
}

// HasStartPrice returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasStartPrice() bool {
	if o != nil && o.StartPrice != nil {
		return true
	}

	return false
}

// SetStartPrice gets a reference to the given int32 and assigns it to the StartPrice field.
func (o *SearchCategoriesItem) SetStartPrice(v int32) {
	o.StartPrice = &v
}

// GetSales returns the Sales field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetSales() int32 {
	if o == nil || o.Sales == nil {
		var ret int32
		return ret
	}
	return *o.Sales
}

// GetSalesOk returns a tuple with the Sales field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetSalesOk() (*int32, bool) {
	if o == nil || o.Sales == nil {
		return nil, false
	}
	return o.Sales, true
}

// HasSales returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasSales() bool {
	if o != nil && o.Sales != nil {
		return true
	}

	return false
}

// SetSales gets a reference to the given int32 and assigns it to the Sales field.
func (o *SearchCategoriesItem) SetSales(v int32) {
	o.Sales = &v
}

// GetSalesPerDayAverage returns the SalesPerDayAverage field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetSalesPerDayAverage() float32 {
	if o == nil || o.SalesPerDayAverage == nil {
		var ret float32
		return ret
	}
	return *o.SalesPerDayAverage
}

// GetSalesPerDayAverageOk returns a tuple with the SalesPerDayAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetSalesPerDayAverageOk() (*float32, bool) {
	if o == nil || o.SalesPerDayAverage == nil {
		return nil, false
	}
	return o.SalesPerDayAverage, true
}

// HasSalesPerDayAverage returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasSalesPerDayAverage() bool {
	if o != nil && o.SalesPerDayAverage != nil {
		return true
	}

	return false
}

// SetSalesPerDayAverage gets a reference to the given float32 and assigns it to the SalesPerDayAverage field.
func (o *SearchCategoriesItem) SetSalesPerDayAverage(v float32) {
	o.SalesPerDayAverage = &v
}

// GetRevenue returns the Revenue field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetRevenue() int32 {
	if o == nil || o.Revenue == nil {
		var ret int32
		return ret
	}
	return *o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetRevenueOk() (*int32, bool) {
	if o == nil || o.Revenue == nil {
		return nil, false
	}
	return o.Revenue, true
}

// HasRevenue returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasRevenue() bool {
	if o != nil && o.Revenue != nil {
		return true
	}

	return false
}

// SetRevenue gets a reference to the given int32 and assigns it to the Revenue field.
func (o *SearchCategoriesItem) SetRevenue(v int32) {
	o.Revenue = &v
}

// GetRevenuePotential returns the RevenuePotential field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetRevenuePotential() int32 {
	if o == nil || o.RevenuePotential == nil {
		var ret int32
		return ret
	}
	return *o.RevenuePotential
}

// GetRevenuePotentialOk returns a tuple with the RevenuePotential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetRevenuePotentialOk() (*int32, bool) {
	if o == nil || o.RevenuePotential == nil {
		return nil, false
	}
	return o.RevenuePotential, true
}

// HasRevenuePotential returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasRevenuePotential() bool {
	if o != nil && o.RevenuePotential != nil {
		return true
	}

	return false
}

// SetRevenuePotential gets a reference to the given int32 and assigns it to the RevenuePotential field.
func (o *SearchCategoriesItem) SetRevenuePotential(v int32) {
	o.RevenuePotential = &v
}

// GetLostProfit returns the LostProfit field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetLostProfit() int32 {
	if o == nil || o.LostProfit == nil {
		var ret int32
		return ret
	}
	return *o.LostProfit
}

// GetLostProfitOk returns a tuple with the LostProfit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetLostProfitOk() (*int32, bool) {
	if o == nil || o.LostProfit == nil {
		return nil, false
	}
	return o.LostProfit, true
}

// HasLostProfit returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasLostProfit() bool {
	if o != nil && o.LostProfit != nil {
		return true
	}

	return false
}

// SetLostProfit gets a reference to the given int32 and assigns it to the LostProfit field.
func (o *SearchCategoriesItem) SetLostProfit(v int32) {
	o.LostProfit = &v
}

// GetLostProfitPercent returns the LostProfitPercent field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetLostProfitPercent() float32 {
	if o == nil || o.LostProfitPercent == nil {
		var ret float32
		return ret
	}
	return *o.LostProfitPercent
}

// GetLostProfitPercentOk returns a tuple with the LostProfitPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetLostProfitPercentOk() (*float32, bool) {
	if o == nil || o.LostProfitPercent == nil {
		return nil, false
	}
	return o.LostProfitPercent, true
}

// HasLostProfitPercent returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasLostProfitPercent() bool {
	if o != nil && o.LostProfitPercent != nil {
		return true
	}

	return false
}

// SetLostProfitPercent gets a reference to the given float32 and assigns it to the LostProfitPercent field.
func (o *SearchCategoriesItem) SetLostProfitPercent(v float32) {
	o.LostProfitPercent = &v
}

// GetDaysInStock returns the DaysInStock field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetDaysInStock() int32 {
	if o == nil || o.DaysInStock == nil {
		var ret int32
		return ret
	}
	return *o.DaysInStock
}

// GetDaysInStockOk returns a tuple with the DaysInStock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetDaysInStockOk() (*int32, bool) {
	if o == nil || o.DaysInStock == nil {
		return nil, false
	}
	return o.DaysInStock, true
}

// HasDaysInStock returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasDaysInStock() bool {
	if o != nil && o.DaysInStock != nil {
		return true
	}

	return false
}

// SetDaysInStock gets a reference to the given int32 and assigns it to the DaysInStock field.
func (o *SearchCategoriesItem) SetDaysInStock(v int32) {
	o.DaysInStock = &v
}

// GetDaysWithSales returns the DaysWithSales field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetDaysWithSales() int32 {
	if o == nil || o.DaysWithSales == nil {
		var ret int32
		return ret
	}
	return *o.DaysWithSales
}

// GetDaysWithSalesOk returns a tuple with the DaysWithSales field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetDaysWithSalesOk() (*int32, bool) {
	if o == nil || o.DaysWithSales == nil {
		return nil, false
	}
	return o.DaysWithSales, true
}

// HasDaysWithSales returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasDaysWithSales() bool {
	if o != nil && o.DaysWithSales != nil {
		return true
	}

	return false
}

// SetDaysWithSales gets a reference to the given int32 and assigns it to the DaysWithSales field.
func (o *SearchCategoriesItem) SetDaysWithSales(v int32) {
	o.DaysWithSales = &v
}

// GetAverageIfInStock returns the AverageIfInStock field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetAverageIfInStock() float32 {
	if o == nil || o.AverageIfInStock == nil {
		var ret float32
		return ret
	}
	return *o.AverageIfInStock
}

// GetAverageIfInStockOk returns a tuple with the AverageIfInStock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetAverageIfInStockOk() (*float32, bool) {
	if o == nil || o.AverageIfInStock == nil {
		return nil, false
	}
	return o.AverageIfInStock, true
}

// HasAverageIfInStock returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasAverageIfInStock() bool {
	if o != nil && o.AverageIfInStock != nil {
		return true
	}

	return false
}

// SetAverageIfInStock gets a reference to the given float32 and assigns it to the AverageIfInStock field.
func (o *SearchCategoriesItem) SetAverageIfInStock(v float32) {
	o.AverageIfInStock = &v
}

// GetThumb returns the Thumb field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetThumb() string {
	if o == nil || o.Thumb == nil {
		var ret string
		return ret
	}
	return *o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetThumbOk() (*string, bool) {
	if o == nil || o.Thumb == nil {
		return nil, false
	}
	return o.Thumb, true
}

// HasThumb returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasThumb() bool {
	if o != nil && o.Thumb != nil {
		return true
	}

	return false
}

// SetThumb gets a reference to the given string and assigns it to the Thumb field.
func (o *SearchCategoriesItem) SetThumb(v string) {
	o.Thumb = &v
}

// GetThumbMiddle returns the ThumbMiddle field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetThumbMiddle() string {
	if o == nil || o.ThumbMiddle == nil {
		var ret string
		return ret
	}
	return *o.ThumbMiddle
}

// GetThumbMiddleOk returns a tuple with the ThumbMiddle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetThumbMiddleOk() (*string, bool) {
	if o == nil || o.ThumbMiddle == nil {
		return nil, false
	}
	return o.ThumbMiddle, true
}

// HasThumbMiddle returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasThumbMiddle() bool {
	if o != nil && o.ThumbMiddle != nil {
		return true
	}

	return false
}

// SetThumbMiddle gets a reference to the given string and assigns it to the ThumbMiddle field.
func (o *SearchCategoriesItem) SetThumbMiddle(v string) {
	o.ThumbMiddle = &v
}

// GetIsFbs returns the IsFbs field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetIsFbs() int32 {
	if o == nil || o.IsFbs == nil {
		var ret int32
		return ret
	}
	return *o.IsFbs
}

// GetIsFbsOk returns a tuple with the IsFbs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetIsFbsOk() (*int32, bool) {
	if o == nil || o.IsFbs == nil {
		return nil, false
	}
	return o.IsFbs, true
}

// HasIsFbs returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasIsFbs() bool {
	if o != nil && o.IsFbs != nil {
		return true
	}

	return false
}

// SetIsFbs gets a reference to the given int32 and assigns it to the IsFbs field.
func (o *SearchCategoriesItem) SetIsFbs(v int32) {
	o.IsFbs = &v
}

// GetSubjectId returns the SubjectId field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetSubjectId() int32 {
	if o == nil || o.SubjectId == nil {
		var ret int32
		return ret
	}
	return *o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetSubjectIdOk() (*int32, bool) {
	if o == nil || o.SubjectId == nil {
		return nil, false
	}
	return o.SubjectId, true
}

// HasSubjectId returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasSubjectId() bool {
	if o != nil && o.SubjectId != nil {
		return true
	}

	return false
}

// SetSubjectId gets a reference to the given int32 and assigns it to the SubjectId field.
func (o *SearchCategoriesItem) SetSubjectId(v int32) {
	o.SubjectId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SearchCategoriesItem) SetUrl(v string) {
	o.Url = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *SearchCategoriesItem) SetCountry(v string) {
	o.Country = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetGender() string {
	if o == nil || o.Gender == nil {
		var ret string
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetGenderOk() (*string, bool) {
	if o == nil || o.Gender == nil {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasGender() bool {
	if o != nil && o.Gender != nil {
		return true
	}

	return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *SearchCategoriesItem) SetGender(v string) {
	o.Gender = &v
}

// GetSkuFirstDate returns the SkuFirstDate field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetSkuFirstDate() string {
	if o == nil || o.SkuFirstDate == nil {
		var ret string
		return ret
	}
	return *o.SkuFirstDate
}

// GetSkuFirstDateOk returns a tuple with the SkuFirstDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetSkuFirstDateOk() (*string, bool) {
	if o == nil || o.SkuFirstDate == nil {
		return nil, false
	}
	return o.SkuFirstDate, true
}

// HasSkuFirstDate returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasSkuFirstDate() bool {
	if o != nil && o.SkuFirstDate != nil {
		return true
	}

	return false
}

// SetSkuFirstDate gets a reference to the given string and assigns it to the SkuFirstDate field.
func (o *SearchCategoriesItem) SetSkuFirstDate(v string) {
	o.SkuFirstDate = &v
}

// GetFirstcommentdate returns the Firstcommentdate field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetFirstcommentdate() string {
	if o == nil || o.Firstcommentdate == nil {
		var ret string
		return ret
	}
	return *o.Firstcommentdate
}

// GetFirstcommentdateOk returns a tuple with the Firstcommentdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetFirstcommentdateOk() (*string, bool) {
	if o == nil || o.Firstcommentdate == nil {
		return nil, false
	}
	return o.Firstcommentdate, true
}

// HasFirstcommentdate returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasFirstcommentdate() bool {
	if o != nil && o.Firstcommentdate != nil {
		return true
	}

	return false
}

// SetFirstcommentdate gets a reference to the given string and assigns it to the Firstcommentdate field.
func (o *SearchCategoriesItem) SetFirstcommentdate(v string) {
	o.Firstcommentdate = &v
}

// GetPicscount returns the Picscount field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetPicscount() int32 {
	if o == nil || o.Picscount == nil {
		var ret int32
		return ret
	}
	return *o.Picscount
}

// GetPicscountOk returns a tuple with the Picscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetPicscountOk() (*int32, bool) {
	if o == nil || o.Picscount == nil {
		return nil, false
	}
	return o.Picscount, true
}

// HasPicscount returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasPicscount() bool {
	if o != nil && o.Picscount != nil {
		return true
	}

	return false
}

// SetPicscount gets a reference to the given int32 and assigns it to the Picscount field.
func (o *SearchCategoriesItem) SetPicscount(v int32) {
	o.Picscount = &v
}

// GetHas3d returns the Has3d field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetHas3d() int32 {
	if o == nil || o.Has3d == nil {
		var ret int32
		return ret
	}
	return *o.Has3d
}

// GetHas3dOk returns a tuple with the Has3d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetHas3dOk() (*int32, bool) {
	if o == nil || o.Has3d == nil {
		return nil, false
	}
	return o.Has3d, true
}

// HasHas3d returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasHas3d() bool {
	if o != nil && o.Has3d != nil {
		return true
	}

	return false
}

// SetHas3d gets a reference to the given int32 and assigns it to the Has3d field.
func (o *SearchCategoriesItem) SetHas3d(v int32) {
	o.Has3d = &v
}

// GetHasvideo returns the Hasvideo field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetHasvideo() int32 {
	if o == nil || o.Hasvideo == nil {
		var ret int32
		return ret
	}
	return *o.Hasvideo
}

// GetHasvideoOk returns a tuple with the Hasvideo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetHasvideoOk() (*int32, bool) {
	if o == nil || o.Hasvideo == nil {
		return nil, false
	}
	return o.Hasvideo, true
}

// HasHasvideo returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasHasvideo() bool {
	if o != nil && o.Hasvideo != nil {
		return true
	}

	return false
}

// SetHasvideo gets a reference to the given int32 and assigns it to the Hasvideo field.
func (o *SearchCategoriesItem) SetHasvideo(v int32) {
	o.Hasvideo = &v
}

// GetCommentsvaluation returns the Commentsvaluation field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCommentsvaluation() float32 {
	if o == nil || o.Commentsvaluation == nil {
		var ret float32
		return ret
	}
	return *o.Commentsvaluation
}

// GetCommentsvaluationOk returns a tuple with the Commentsvaluation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCommentsvaluationOk() (*float32, bool) {
	if o == nil || o.Commentsvaluation == nil {
		return nil, false
	}
	return o.Commentsvaluation, true
}

// HasCommentsvaluation returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCommentsvaluation() bool {
	if o != nil && o.Commentsvaluation != nil {
		return true
	}

	return false
}

// SetCommentsvaluation gets a reference to the given float32 and assigns it to the Commentsvaluation field.
func (o *SearchCategoriesItem) SetCommentsvaluation(v float32) {
	o.Commentsvaluation = &v
}

// GetCardratingval returns the Cardratingval field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCardratingval() int32 {
	if o == nil || o.Cardratingval == nil {
		var ret int32
		return ret
	}
	return *o.Cardratingval
}

// GetCardratingvalOk returns a tuple with the Cardratingval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCardratingvalOk() (*int32, bool) {
	if o == nil || o.Cardratingval == nil {
		return nil, false
	}
	return o.Cardratingval, true
}

// HasCardratingval returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCardratingval() bool {
	if o != nil && o.Cardratingval != nil {
		return true
	}

	return false
}

// SetCardratingval gets a reference to the given int32 and assigns it to the Cardratingval field.
func (o *SearchCategoriesItem) SetCardratingval(v int32) {
	o.Cardratingval = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetPosition() int32 {
	if o == nil || o.Position == nil {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetPositionOk() (*int32, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *SearchCategoriesItem) SetPosition(v int32) {
	o.Position = &v
}

// GetCategoriesLastCount returns the CategoriesLastCount field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCategoriesLastCount() string {
	if o == nil || o.CategoriesLastCount == nil {
		var ret string
		return ret
	}
	return *o.CategoriesLastCount
}

// GetCategoriesLastCountOk returns a tuple with the CategoriesLastCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCategoriesLastCountOk() (*string, bool) {
	if o == nil || o.CategoriesLastCount == nil {
		return nil, false
	}
	return o.CategoriesLastCount, true
}

// HasCategoriesLastCount returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCategoriesLastCount() bool {
	if o != nil && o.CategoriesLastCount != nil {
		return true
	}

	return false
}

// SetCategoriesLastCount gets a reference to the given string and assigns it to the CategoriesLastCount field.
func (o *SearchCategoriesItem) SetCategoriesLastCount(v string) {
	o.CategoriesLastCount = &v
}

// GetGraph returns the Graph field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetGraph() []int32 {
	if o == nil || o.Graph == nil {
		var ret []int32
		return ret
	}
	return o.Graph
}

// GetGraphOk returns a tuple with the Graph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetGraphOk() ([]int32, bool) {
	if o == nil || o.Graph == nil {
		return nil, false
	}
	return o.Graph, true
}

// HasGraph returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasGraph() bool {
	if o != nil && o.Graph != nil {
		return true
	}

	return false
}

// SetGraph gets a reference to the given []int32 and assigns it to the Graph field.
func (o *SearchCategoriesItem) SetGraph(v []int32) {
	o.Graph = v
}

// GetCategoryGraph returns the CategoryGraph field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetCategoryGraph() []int32 {
	if o == nil || o.CategoryGraph == nil {
		var ret []int32
		return ret
	}
	return o.CategoryGraph
}

// GetCategoryGraphOk returns a tuple with the CategoryGraph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetCategoryGraphOk() ([]int32, bool) {
	if o == nil || o.CategoryGraph == nil {
		return nil, false
	}
	return o.CategoryGraph, true
}

// HasCategoryGraph returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasCategoryGraph() bool {
	if o != nil && o.CategoryGraph != nil {
		return true
	}

	return false
}

// SetCategoryGraph gets a reference to the given []int32 and assigns it to the CategoryGraph field.
func (o *SearchCategoriesItem) SetCategoryGraph(v []int32) {
	o.CategoryGraph = v
}

// GetStocksGraph returns the StocksGraph field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetStocksGraph() []int32 {
	if o == nil || o.StocksGraph == nil {
		var ret []int32
		return ret
	}
	return o.StocksGraph
}

// GetStocksGraphOk returns a tuple with the StocksGraph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetStocksGraphOk() ([]int32, bool) {
	if o == nil || o.StocksGraph == nil {
		return nil, false
	}
	return o.StocksGraph, true
}

// HasStocksGraph returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasStocksGraph() bool {
	if o != nil && o.StocksGraph != nil {
		return true
	}

	return false
}

// SetStocksGraph gets a reference to the given []int32 and assigns it to the StocksGraph field.
func (o *SearchCategoriesItem) SetStocksGraph(v []int32) {
	o.StocksGraph = v
}

// GetPriceGraph returns the PriceGraph field value if set, zero value otherwise.
func (o *SearchCategoriesItem) GetPriceGraph() []int32 {
	if o == nil || o.PriceGraph == nil {
		var ret []int32
		return ret
	}
	return o.PriceGraph
}

// GetPriceGraphOk returns a tuple with the PriceGraph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCategoriesItem) GetPriceGraphOk() ([]int32, bool) {
	if o == nil || o.PriceGraph == nil {
		return nil, false
	}
	return o.PriceGraph, true
}

// HasPriceGraph returns a boolean if a field has been set.
func (o *SearchCategoriesItem) HasPriceGraph() bool {
	if o != nil && o.PriceGraph != nil {
		return true
	}

	return false
}

// SetPriceGraph gets a reference to the given []int32 and assigns it to the PriceGraph field.
func (o *SearchCategoriesItem) SetPriceGraph(v []int32) {
	o.PriceGraph = v
}

func (o SearchCategoriesItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Brand != nil {
		toSerialize["brand"] = o.Brand
	}
	if o.Seller != nil {
		toSerialize["seller"] = o.Seller
	}
	if o.SupplierId != nil {
		toSerialize["supplier_id"] = o.SupplierId
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	if o.CategoryPosition != nil {
		toSerialize["category_position"] = o.CategoryPosition
	}
	if o.PosData != nil {
		toSerialize["pos_data"] = o.PosData
	}
	if o.Color != nil {
		toSerialize["color"] = o.Color
	}
	if o.Balance != nil {
		toSerialize["balance"] = o.Balance
	}
	if o.BalanceFbs != nil {
		toSerialize["balance_fbs"] = o.BalanceFbs
	}
	if o.Comments != nil {
		toSerialize["comments"] = o.Comments
	}
	if o.Rating != nil {
		toSerialize["rating"] = o.Rating
	}
	if o.FinalPrice != nil {
		toSerialize["final_price"] = o.FinalPrice
	}
	if o.FinalPriceMax != nil {
		toSerialize["final_price_max"] = o.FinalPriceMax
	}
	if o.FinalPriceMin != nil {
		toSerialize["final_price_min"] = o.FinalPriceMin
	}
	if o.FinalPriceAverage != nil {
		toSerialize["final_price_average"] = o.FinalPriceAverage
	}
	if o.BasicSale != nil {
		toSerialize["basic_sale"] = o.BasicSale
	}
	if o.BasicPrice != nil {
		toSerialize["basic_price"] = o.BasicPrice
	}
	if o.PromoSale != nil {
		toSerialize["promo_sale"] = o.PromoSale
	}
	if o.ClientSale != nil {
		toSerialize["client_sale"] = o.ClientSale
	}
	if o.ClientPrice != nil {
		toSerialize["client_price"] = o.ClientPrice
	}
	if o.StartPrice != nil {
		toSerialize["start_price"] = o.StartPrice
	}
	if o.Sales != nil {
		toSerialize["sales"] = o.Sales
	}
	if o.SalesPerDayAverage != nil {
		toSerialize["sales_per_day_average"] = o.SalesPerDayAverage
	}
	if o.Revenue != nil {
		toSerialize["revenue"] = o.Revenue
	}
	if o.RevenuePotential != nil {
		toSerialize["revenue_potential"] = o.RevenuePotential
	}
	if o.LostProfit != nil {
		toSerialize["lost_profit"] = o.LostProfit
	}
	if o.LostProfitPercent != nil {
		toSerialize["lost_profit_percent"] = o.LostProfitPercent
	}
	if o.DaysInStock != nil {
		toSerialize["days_in_stock"] = o.DaysInStock
	}
	if o.DaysWithSales != nil {
		toSerialize["days_with_sales"] = o.DaysWithSales
	}
	if o.AverageIfInStock != nil {
		toSerialize["average_if_in_stock"] = o.AverageIfInStock
	}
	if o.Thumb != nil {
		toSerialize["thumb"] = o.Thumb
	}
	if o.ThumbMiddle != nil {
		toSerialize["thumb_middle"] = o.ThumbMiddle
	}
	if o.IsFbs != nil {
		toSerialize["is_fbs"] = o.IsFbs
	}
	if o.SubjectId != nil {
		toSerialize["subject_id"] = o.SubjectId
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	if o.Gender != nil {
		toSerialize["gender"] = o.Gender
	}
	if o.SkuFirstDate != nil {
		toSerialize["sku_first_date"] = o.SkuFirstDate
	}
	if o.Firstcommentdate != nil {
		toSerialize["firstcommentdate"] = o.Firstcommentdate
	}
	if o.Picscount != nil {
		toSerialize["picscount"] = o.Picscount
	}
	if o.Has3d != nil {
		toSerialize["has3d"] = o.Has3d
	}
	if o.Hasvideo != nil {
		toSerialize["hasvideo"] = o.Hasvideo
	}
	if o.Commentsvaluation != nil {
		toSerialize["commentsvaluation"] = o.Commentsvaluation
	}
	if o.Cardratingval != nil {
		toSerialize["cardratingval"] = o.Cardratingval
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.CategoriesLastCount != nil {
		toSerialize["categories_last_count"] = o.CategoriesLastCount
	}
	if o.Graph != nil {
		toSerialize["graph"] = o.Graph
	}
	if o.CategoryGraph != nil {
		toSerialize["category_graph"] = o.CategoryGraph
	}
	if o.StocksGraph != nil {
		toSerialize["stocks_graph"] = o.StocksGraph
	}
	if o.PriceGraph != nil {
		toSerialize["price_graph"] = o.PriceGraph
	}
	return json.Marshal(toSerialize)
}

type NullableSearchCategoriesItem struct {
	value *SearchCategoriesItem
	isSet bool
}

func (v NullableSearchCategoriesItem) Get() *SearchCategoriesItem {
	return v.value
}

func (v *NullableSearchCategoriesItem) Set(val *SearchCategoriesItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCategoriesItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCategoriesItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCategoriesItem(val *SearchCategoriesItem) *NullableSearchCategoriesItem {
	return &NullableSearchCategoriesItem{value: val, isSet: true}
}

func (v NullableSearchCategoriesItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCategoriesItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


