/*
mpstats

MPStats API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetItemsBatchRequestBody struct for GetItemsBatchRequestBody
type GetItemsBatchRequestBody struct {
	// Массив SKU товаров, не более 200 в одном запросе
	Ids []int32 `json:"ids"`
}

// NewGetItemsBatchRequestBody instantiates a new GetItemsBatchRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetItemsBatchRequestBody(ids []int32) *GetItemsBatchRequestBody {
	this := GetItemsBatchRequestBody{}
	this.Ids = ids
	return &this
}

// NewGetItemsBatchRequestBodyWithDefaults instantiates a new GetItemsBatchRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetItemsBatchRequestBodyWithDefaults() *GetItemsBatchRequestBody {
	this := GetItemsBatchRequestBody{}
	return &this
}

// GetIds returns the Ids field value
func (o *GetItemsBatchRequestBody) GetIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *GetItemsBatchRequestBody) GetIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *GetItemsBatchRequestBody) SetIds(v []int32) {
	o.Ids = v
}

func (o GetItemsBatchRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ids"] = o.Ids
	}
	return json.Marshal(toSerialize)
}

type NullableGetItemsBatchRequestBody struct {
	value *GetItemsBatchRequestBody
	isSet bool
}

func (v NullableGetItemsBatchRequestBody) Get() *GetItemsBatchRequestBody {
	return v.value
}

func (v *NullableGetItemsBatchRequestBody) Set(val *GetItemsBatchRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItemsBatchRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItemsBatchRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItemsBatchRequestBody(val *GetItemsBatchRequestBody) *NullableGetItemsBatchRequestBody {
	return &NullableGetItemsBatchRequestBody{value: val, isSet: true}
}

func (v NullableGetItemsBatchRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItemsBatchRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


